### ISSUE TITLE
Port mapping error when trying to view table

### ISSUE THREAD

**Issue by danibjor** [CloudBoost/dashboard#12]
Tried the latest docker version in my dev-environment.

When clicking a table (also user/installation etc) it changes the port from 1440 to 3333 - thus a 404 error is shown and you cannot browse the data in the tables.

**Comment by shubhamqweasd** [comment]
@danibjor , we have updated the docker-cloud.yml file , it should now work.

**Comment by danibjor** [comment]
There is still some issues here. 

When i have the list of tables open

http://10.0.0.47:1440/#/app-id/table

- then click on a table to browse the data, it loads the page

http://10.0.0.47:3333/#/app-id/tableName

the table viewer briefly shows up, then the page is automatically redirected to 

https://dashboard.cloudboost.io/#/

**Comment by danibjor** [comment]
It's the same running on a local docker instance on my MacBook as when running on the dev-server testet in the previous comment here.

**Comment by shubhamqweasd** [comment]
should be fixed now :smile:  , please check

**Comment by danibjor** [comment]
Looking good! Thanks :)
