### ISSUE TITLE
Redirect from port 1440 to port 1447?

### ISSUE THREAD

**Issue by crazy4groovy** [CloudBoost/dashboard#15]
I am seeing an issue.

I try to visit the dashboard running on port 1440. I briefly see the main page, then "cannot connect to server" message, then a redirect to port 1447.

I do have the API running on port 4730 (response tells me to visit the dashboard on port 1440).

Something I'm missing?

**Comment by nawazdhandala** [comment]
Hi, Can you see Login screen at port 1447?

**Comment by crazy4groovy** [comment]
No, the browser says "this site can't be reached"

(at that port)

**Comment by nawazdhandala** [comment]
Can you share your docker stack / cloud file?

- Nawaz

On 27 Jan 2017, 10:30 AM +0530, crazy4groovy <notifications@github.com>, wrote:

No, the browser says "this site can't be reached"

(at that port)

**Comment by crazy4groovy** [comment]
```
user@ubuntu:~# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
b28fb4dfbd03        mongo               "/entrypoint.sh mo..."   4 days ago          Up 4 days           0.0.0.0:27017->27017/tcp   mongo1
8ce92333cdfa        redis               "docker-entrypoint..."   4 days ago          Up 4 days           0.0.0.0:6379->6379/tcp     redis1
```

```
user@ubuntu:~/apps/cloudboost/config# cat cloudboost.json
{
 "mongo" : [{
   "host" : "localhost",
   "port" : "27017"
 }],
 "redis" : [{
       "host" : "localhost",
       "port" : 6379
   }]
}
```

**Comment by nawazdhandala** [comment]
I think you dont have an account container. Can you check this repo out and follow instructions : github.com/cloudboot/docker 

Please feel free to re-open this issue if it does not solve your problem. :)

**Comment by sunanxiang** [comment]
do you resolve that problem? I have the same problem to you but don't know why. @ @crazy4groovy

**Comment by nawazdhandala** [comment]
@sunanxiang If you're self hosting CloudBoost, only API on port 4730 is open source. You cannot use any UI repos. To work with UI, you can sign up and use CloudBoost.io

**Comment by HoseinGhanbari** [comment]
Hello !
How can I connect the dashboard GUI running on port 1440 to the API running on port 4730 ?
I'm using docker to run the cloudboost on my system.
When i try to open "http://localhost:1440/" it says "Cannot connect to server. Please try again." and after some seconds, redirects to "http://localhost:1447/" with the "This site can’t be reached" error.
@nawazdhandala What you mean by "I think you dont have an account container" ?
@nawazdhandala If we can not connect the API server to the Dashboard with self hosting CloudBoost, what's the purpose of sharing the dashboard repository and its usage ?

**Comment by shubhamqweasd** [comment]
@HoseinGhanbari , dashboard GUI was open source a few months back, but now we have decided to closed source it. The codebase you have is probably very old and is not updated, so don't expect that to work. Currently only CloudBoost API and the SDK are opensource, UI's are like add-on features over our service and to use them you need to signup at CloudBoost.io

**Comment by shubhamqweasd** [comment]
@HoseinGhanbari , We will be deleting this old dashboard repository in a few days :)

**Comment by HoseinGhanbari** [comment]
@shubhamqweasd 
Thank you very much for the clarification! :)
Your explanation helped me a lot.
